---
name: "Question"
description: I have a question, or need a help with the configuration of the integration or Lovelace
labels: "question"
assignees: "cjramseyer"
body:
  - type: checkboxes
    attributes:
      label: Before you submit a new bug report, please check that
      options:
        - label: I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
          required: true
  - type: textarea
    attributes:
      label: "Write your question here"
      description: "If your question is about the configuration, please make it clear 
    if you need help with the configuration of integration, 
    or lovelace card configuration
    or perhaps an automation?"
    validations:
      required: true
