blueprint:
  name: Exclude dates
  description: >-
    This automation is triggered from the `garbage_collection` integration by event `garbage_collection_loaded`,
    during the device state update. 

    It PROCESSES DATA SENT WITH THE EVENT, and then FINISHES THE UPDATE.
    DO NOT CALL THIS SERVICE MANUALLY, IT WON'T WORK (it won't have the data).

    Also, make sure the INTEGRATION IS CONFIGURED FOR `manual_update`
    (that will disable the state update by the integration and pass it to this automation).


    It removes events on provided set of dates. Enter one date per line. For example:

    2022-01-03

    2022-04-04

    2022-07-04

    2022-10-03


    After updating the list, make sure to trigger the entity update. 
    The sensors are normally updated once a day, or when Home Assistant starts.
    The update can be triggered by updating the integration configuration (just hit configure and submit).
  domain: automation
  source_url: https://github.com/bruxy70/Garbage-Collection/blob/master/blueprints/exclude.yaml
  input:
    garbage_collection_entity:
      name: Garbage Collection Entity
      description: Triggered by the event for this entity.
      selector:
        entity:
          integration: garbage_collection
    exclude:
      name: Set of dates to exclude
      description: |-
        List of dates in format yyyy-mm-dd, one date per line.
      selector:
        text:
          multiline: true
mode: parallel
trigger:
  - platform: event
    event_type: garbage_collection_loaded
    event_data:
      entity_id: !input garbage_collection_entity
action:
  - variables:
      exclude: !input exclude
  - alias: "Iterate through the lines to exclude"
    repeat:
      for_each: "{{ exclude.split('\n') }}"
      sequence:
        - alias: "Remove the date"
          service: garbage_collection.remove_date
          data:
            entity_id: "{{ trigger.event.data.entity_id }}"
            date: "{{ repeat.item }}"
  - alias: "Update the garbage_collection entity"
    service: garbage_collection.update_state
    data:
      entity_id: "{{ trigger.event.data.entity_id }}"
