blueprint:
  name: Garbage collection offset
  description: >-
    This automation is triggered from the `garbage_collection` integration by event `garbage_collection_loaded`,
    during the device state update. 

    It PROCESSES DATA SENT WITH THE EVENT, and then FINISHES THE UPDATE.
    DO NOT CALL THIS SERVICE MANUALLY, IT WON'T WORK (it won't have the data).

    Also, make sure the INTEGRATION IS CONFIGURED FOR `manual_update`
    (that will disable the state update by the integration and pass it to this automation).


    It loops through the calculated dates and offset them by a constant number of days.


    The sensors are normally updated once a day, or when Home Assistant starts.
    The update can be triggered by updating the integration configuration (just hit configure and submit).
  domain: automation
  source_url: https://github.com/bruxy70/Garbage-Collection/blob/master/blueprints/offset.yaml
  input:
    garbage_collection_entity:
      name: Garbage Collection Entity
      description: Triggered by the event for this entity.
      selector:
        entity:
          integration: garbage_collection
    offset:
      name: Offset (number of days)
      description: >-
        Offset the collection by given number of days. This can be used 
        for example to schedule an event for the last Wednesday each month.
        To do that, configuring it for first Wednesday each month and then offset by -7 days.
      selector:
        number:
          min: -7
          max: 7
          mode: box
mode: parallel
trigger:
  - platform: event
    event_type: garbage_collection_loaded
    event_data:
      entity_id: !input garbage_collection_entity
action:
  - variables:
      offset: !input offset
  - alias: "Iterate through the dates"
    repeat:
      for_each: "{{ trigger.event.data.collection_dates }}"
      sequence:
        - alias: "Move the date"
          service: garbage_collection.offset_date
          data:
            entity_id: "{{ trigger.event.data.entity_id }}"
            date: "{{ repeat.item }}"
            offset: "{{ offset }}"
  - alias: "Update the garbage_collection entity"
    service: garbage_collection.update_state
    data:
      entity_id: "{{ trigger.event.data.entity_id }}"
